"""Onboarding wizard router.

Endpoints
---------
GET  /onboarding/state             — hydrate the wizard (resume support)
POST /onboarding/step/{n}          — persist one step's payload
POST /onboarding/complete          — finalise: stamp `onboarding_completed_at`
POST /onboarding/seed-sample-data  — owner-only: insert the deterministic
                                     fixture so the dashboard isn't empty

Every mutation calls :func:`record_audit` and best-effort publishes an event
on the org's channel. The state machine itself lives in
``app.services.onboarding.state`` and is unit-tested in isolation; this
module is the I/O layer.
"""
from __future__ import annotations

import logging
from datetime import UTC, date, datetime
from typing import Annotated, Any

from fastapi import APIRouter, Body, HTTPException, Path
from pydantic import Field, TypeAdapter, ValidationError

from app.api.schemas import (
    OnboardingCaptureDTO,
    OnboardingCompleteResponse,
    OnboardingSeedSampleResponse,
    OnboardingStateDTO,
    OnboardingStepResponse,
    OrgDTO,
)
from app.deps import CurrentOrg, CurrentUser, DbSession, requires_role
from app.models.org import Membership, Org, Persona
from app.scripts.seed_dev_data import seed_org
from app.services.events import EventType
from app.services.events import publish_event_best_effort as publish_event
from app.services.onboarding.state import (
    OnboardingCapture,
    OnboardingStepDataPayload,
    OnboardingStepOrgPayload,
    OnboardingStepPersonaPayload,
    StateValidationError,
    next_step,
)
from app.utils.audit import record_audit

router = APIRouter()
log = logging.getLogger(__name__)


_StepPayloadAdapter: TypeAdapter[
    OnboardingStepOrgPayload | OnboardingStepPersonaPayload | OnboardingStepDataPayload
] = TypeAdapter(
    Annotated[
        OnboardingStepOrgPayload
        | OnboardingStepPersonaPayload
        | OnboardingStepDataPayload,
        Field(discriminator="step"),
    ]
)


def _safe_publish(org_id: str, event_type: str, payload: dict[str, Any]) -> None:
    try:
        publish_event(org_id, event_type, payload)
    except Exception:  # noqa: BLE001
        log.exception("publish_event failed for %s", event_type)


def _capture_from_org(org: Org) -> OnboardingCapture:
    """Reconstruct the running wizard state from the org row.

    Step 1 sets the org name + currency + fiscal-year — we detect "step 1
    done" by the org name no longer matching the autogenerated placeholder
    ``"<email>'s Org"`` produced by /auth/register. Step 2 sets
    ``orgs.persona``. Step 3 has no persisted state (the data-source choice
    is consumed at the moment of submission); we infer "step 3 done" from
    ``onboarding_completed_at`` being set.
    """
    persona: Persona | None = None
    if org.persona:
        try:
            persona = Persona(org.persona)
        except ValueError:
            persona = None

    step_1_done = not org.name.endswith("'s Org") or persona is not None
    step_3_done = org.onboarding_completed_at is not None

    return OnboardingCapture(
        org_name=org.name if step_1_done else None,
        base_currency=org.base_currency if step_1_done else None,
        fiscal_year_start_month=org.fiscal_year_start_month if step_1_done else None,
        persona=persona,
        data_choice="start_empty" if step_3_done else None,
    )


def _capture_to_dto(capture: OnboardingCapture) -> OnboardingCaptureDTO:
    return OnboardingCaptureDTO(
        org_name=capture.org_name,
        base_currency=capture.base_currency,
        fiscal_year_start_month=capture.fiscal_year_start_month,
        persona=capture.persona.value if capture.persona else None,
        data_choice=capture.data_choice,
    )


def _resolve_step_number(capture: OnboardingCapture, completed_at: datetime | None) -> int:
    if completed_at is not None:
        return 4
    if capture.persona is None and capture.org_name is None:
        return 1
    if capture.persona is None:
        return 2
    return 3


@router.get("/state", response_model=OnboardingStateDTO)
async def get_state(org: CurrentOrg) -> OnboardingStateDTO:
    capture = _capture_from_org(org)
    step = _resolve_step_number(capture, org.onboarding_completed_at)
    return OnboardingStateDTO(
        step=step,
        completed_at=org.onboarding_completed_at,
        captured=_capture_to_dto(capture),
    )


@router.post("/step/{n}", response_model=OnboardingStepResponse)
async def post_step(
    n: Annotated[int, Path(ge=1, le=3)],
    body: Annotated[dict[str, Any], Body(...)],
    org: CurrentOrg,
    user: CurrentUser,
    session: DbSession,
) -> OnboardingStepResponse:
    if org.onboarding_completed_at is not None:
        raise HTTPException(
            status_code=409,
            detail={"code": "already_completed", "message": "Onboarding already completed"},
        )

    # Parse the payload through the discriminated union.
    try:
        payload = _StepPayloadAdapter.validate_python(body)
    except (ValidationError, StateValidationError) as exc:
        raise HTTPException(status_code=422, detail={"code": "invalid_payload", "message": str(exc)}) from exc

    capture = _capture_from_org(org)
    try:
        result = next_step(current_step=n, capture=capture, payload=payload)
    except StateValidationError as exc:
        raise HTTPException(status_code=422, detail={"code": "invalid_transition", "message": str(exc)}) from exc

    # Mirror new capture onto the org row.
    if result.capture.org_name is not None:
        org.name = result.capture.org_name
    if result.capture.base_currency is not None:
        org.base_currency = result.capture.base_currency
    if result.capture.fiscal_year_start_month is not None:
        org.fiscal_year_start_month = result.capture.fiscal_year_start_month
    if result.capture.persona is not None:
        org.persona = result.capture.persona.value

    await session.flush()
    await record_audit(
        session,
        org_id=org.id,
        user_id=user.id,
        action="onboarding.step_completed",
        entity_type="org",
        entity_id=org.id,
        details={"step": n, "capture": _capture_to_dto(result.capture).model_dump()},
    )
    _safe_publish(org.id, EventType.ONBOARDING_STEP_COMPLETED.value, {"step": n})

    return OnboardingStepResponse(
        step=result.next_step,
        completed_at=org.onboarding_completed_at,
        captured=_capture_to_dto(result.capture),
    )


@router.post("/complete", response_model=OnboardingCompleteResponse)
async def post_complete(
    org: CurrentOrg,
    user: CurrentUser,
    session: DbSession,
) -> OnboardingCompleteResponse:
    if org.onboarding_completed_at is not None:
        # Idempotent: re-completion just returns the existing timestamp.
        return OnboardingCompleteResponse(
            completed_at=org.onboarding_completed_at,
            org=OrgDTO.model_validate(org),
        )

    capture = _capture_from_org(org)
    # The state machine guards against completing with missing captures.
    # We treat data_choice as implicitly "start_empty" if the user reached
    # step 4 via the API without explicitly seeding — the wizard always
    # sends a step-3 payload before complete.
    if capture.data_choice is None:
        capture = OnboardingCapture(
            org_name=capture.org_name,
            base_currency=capture.base_currency,
            fiscal_year_start_month=capture.fiscal_year_start_month,
            persona=capture.persona,
            data_choice="start_empty",
        )
    try:
        next_step(current_step=4, capture=capture, payload=None)
    except StateValidationError as exc:
        raise HTTPException(
            status_code=422,
            detail={"code": "incomplete_capture", "message": str(exc)},
        ) from exc

    now = datetime.now(UTC)
    org.onboarding_completed_at = now
    await session.flush()
    await record_audit(
        session,
        org_id=org.id,
        user_id=user.id,
        action="onboarding.completed",
        entity_type="org",
        entity_id=org.id,
        details={"capture": _capture_to_dto(capture).model_dump()},
    )
    _safe_publish(org.id, EventType.ONBOARDING_COMPLETED.value, {"org_id": org.id})

    return OnboardingCompleteResponse(
        completed_at=now,
        org=OrgDTO.model_validate(org),
    )


@router.post("/seed-sample-data", response_model=OnboardingSeedSampleResponse)
async def post_seed_sample_data(
    org: CurrentOrg,
    user: CurrentUser,
    session: DbSession,
    _membership: Membership = requires_role("owner"),
) -> OnboardingSeedSampleResponse:
    """Owner-only: insert the deterministic fixture for this org."""
    today = date.today()
    stats = await seed_org(session, org.id, today=today, commit=False)
    await session.flush()

    await record_audit(
        session,
        org_id=org.id,
        user_id=user.id,
        action="onboarding.sample_data_seeded",
        entity_type="org",
        entity_id=org.id,
        details={
            "transactions_inserted": stats.transactions_inserted,
            "invoices_inserted": stats.invoices_inserted,
            "customers_inserted": stats.customers_inserted,
            "commitments_inserted": stats.commitments_inserted,
        },
    )
    _safe_publish(org.id, EventType.ONBOARDING_SAMPLE_DATA_SEEDED.value, {"org_id": org.id})

    return OnboardingSeedSampleResponse(
        transactions_inserted=stats.transactions_inserted,
        invoices_inserted=stats.invoices_inserted,
        customers_inserted=stats.customers_inserted,
        commitments_inserted=stats.commitments_inserted,
    )
